import { NextRequest, NextResponse } from 'next/server'
import fs from 'fs'
import path from 'path'
import { WORKSPACE_ROOT } from '@/server/awon/workspace'

// serves verification screenshots from the sandboxed workspace verify/ tree.
// every path component is strictly validated: run ids and file names are
// generated by the kernel (never user input) and re-checked here anyway.
const RUN_RE = /^run-[a-z0-9]+-[a-z0-9]+$/
const NAME_RE = /^(desktop|tablet|mobile|cms-[a-z]+)\.png$/

export async function GET(req: NextRequest) {
  const run = req.nextUrl.searchParams.get('run') ?? ''
  const name = req.nextUrl.searchParams.get('name') ?? ''
  if (!RUN_RE.test(run) || !NAME_RE.test(name)) {
    return new NextResponse('AWON: bad verify asset request', { status: 400 })
  }
  const file = path.join(WORKSPACE_ROOT, 'verify', run, name)
  // defense in depth: the resolved path must sit inside <workspace>/verify
  if (!path.resolve(file).startsWith(path.resolve(WORKSPACE_ROOT, 'verify') + path.sep)) {
    return new NextResponse('AWON: bad verify asset request', { status: 400 })
  }
  try {
    const buf = fs.readFileSync(file)
    return new NextResponse(new Uint8Array(buf), {
      headers: { 'Content-Type': 'image/png', 'Cache-Control': 'private, max-age=3600' },
    })
  } catch {
    return new NextResponse('AWON: verify asset not found', { status: 404 })
  }
}
