// ROYAL RED WordPress builder (Round 6, Section 6).
//
// Produces a real, installable WordPress theme: a proper theme folder with
// style.css (with the WordPress theme header comment), functions.php with the
// theme setup + wp_enqueue_scripts + register_nav_menus, and template files
// (front-page, index, single, page, archive, search, 404, header, footer).
// Two packaging modes per the spec:
//   theme  - the bare theme folder, zipped, upload via WP admin
//   full   - theme + a plugins manifest + recommended config readme, zipped
//
// HONESTY LAW: this sandbox has no PHP runtime and no WordPress install, so
// the builder runs a static Theme-Check-style audit and the receipt carries
// the label "verification pending real WordPress". It never claims a live
// WordPress pass it did not run. If a real WordPress target is provided
// later, the verify seam is where the live audit lands.
//
// Every copy string passes through the text law: no emojis, no em/en dashes.

import { buildZip } from '../zip'
import { enforceTextLaw } from '../text-law'

export interface WpThemeInput {
  prompt: string
  brand?: string
  tagline?: string
  industry?: string
  palette?: { primary: string; accent: string; background: string; text: string }
  fonts?: { display: string; body: string }
  package?: 'theme' | 'full'
}

export interface WpCheck {
  name: string
  pass: boolean
  detail?: string
}

export interface WpThemeReport {
  slug: string
  themeName: string
  files: { path: string; content: string }[]
  checks: WpCheck[]
  status: 'static-audit-pass' | 'static-audit-fail'
  verificationLabel: 'verification pending real WordPress'
  summary: string
}

const DEFAULT_PALETTE = { primary: '#7f1d1d', accent: '#b8860b', background: '#faf5f0', text: '#2b211a' }
const DEFAULT_FONTS = { display: 'Cormorant Garamond, Georgia, serif', body: 'Inter, system-ui, sans-serif' }

function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40) || 'royal-theme'
  )
}

// derive a display name + honest default copy from the prompt
function deriveIdentity(input: WpThemeInput) {
  const law = (s: string) => enforceTextLaw(s).text
  const brand = law(
    input.brand?.trim() ||
      input.prompt
        .split(/\s+/)
        .slice(0, 3)
        .map((w) => (w[0] ? w[0].toUpperCase() + w.slice(1) : w))
        .join(' ') ||
      'Royal Site',
  )
  const tagline = law(input.tagline?.trim() || `Where ${input.industry ?? 'the craft'} meets dedication`)
  return { brand, tagline }
}

export function generateWpTheme(input: WpThemeInput): WpThemeReport {
  const identity = deriveIdentity(input)
  const slug = slugify(input.brand ?? input.prompt)
  const fnPrefix = slug.replace(/-/g, '_')
  const palette = { ...DEFAULT_PALETTE, ...(input.palette ?? {}) }
  const fonts = { ...DEFAULT_FONTS, ...(input.fonts ?? {}) }
  const industry = input.industry?.trim() || 'portfolio'
  const law = (s: string) => enforceTextLaw(s).text

  const files: { path: string; content: string }[] = []
  const push = (path: string, content: string) => files.push({ path, content: law(content) })

  // ---- style.css: the WordPress theme header is mandatory ----
  push(
    'style.css',
    `/*
Theme Name: ${identity.brand}
Theme URI: https://royalred.local/${slug}
Author: Royal Red
Author URI: https://royalred.local
Description: A premium ${industry} theme generated by ROYAL RED. Signature typography, per-section color law, and an honest, accessible structure.
Version: 1.0.0
Requires at least: 6.0
Tested up to: 6.7
Requires PHP: 7.4
License: Proprietary (Royal Red)
Text Domain: ${slug}
Tags: ${industry}, custom-menu, custom-logo, featured-images, translation-ready
*/

:root {
  --rr-primary: ${palette.primary};
  --rr-accent: ${palette.accent};
  --rr-bg: ${palette.background};
  --rr-text: ${palette.text};
  --rr-font-display: ${fonts.display};
  --rr-font-body: ${fonts.body};
}

* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--rr-bg);
  color: var(--rr-text);
  font-family: var(--rr-font-body);
  line-height: 1.6;
}
h1, h2, h3 { font-family: var(--rr-font-display); line-height: 1.15; }
a { color: var(--rr-primary); }
.rr-wrap { max-width: 1100px; margin: 0 auto; padding: 0 1.25rem; }
.rr-header { border-bottom: 1px solid color-mix(in srgb, var(--rr-accent) 30%, transparent); background: color-mix(in srgb, var(--rr-bg) 92%, white); }
.rr-nav { display: flex; align-items: center; gap: 1.25rem; padding: 1rem 0; flex-wrap: wrap; }
.rr-nav a { text-decoration: none; font-weight: 600; }
.rr-hero { background: linear-gradient(160deg, color-mix(in srgb, var(--rr-primary) 12%, var(--rr-bg)), var(--rr-bg) 70%); padding: 5rem 0 4rem; }
.rr-hero h1 { font-size: clamp(2.2rem, 5vw, 3.6rem); margin: 0 0 0.6rem; }
.rr-section { padding: 3.5rem 0; }
.rr-section.alt { background: color-mix(in srgb, var(--rr-accent) 8%, var(--rr-bg)); }
.rr-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1.5rem; }
.rr-card { background: #fffdf8; border: 1px solid color-mix(in srgb, var(--rr-accent) 25%, transparent); border-radius: 1rem; padding: 1.4rem; }
.rr-footer { margin-top: 4rem; padding: 2.5rem 0; border-top: 1px solid color-mix(in srgb, var(--rr-accent) 30%, transparent); color: color-mix(in srgb, var(--rr-text) 75%, transparent); }
.rr-footer a { margin-right: 1rem; }
.entry-content img { max-width: 100%; height: auto; }
.wp-block-button__link { background: var(--rr-primary); }
@media (prefers-reduced-motion: reduce) { * { animation: none !important; transition: none !important; } }
`,
  )

  // ---- functions.php: setup, enqueues, menus, supports ----
  push(
    'functions.php',
    `<?php
/**
 * ${identity.brand} theme setup. Generated by ROYAL RED.
 * All styles and scripts load through wp_enqueue_scripts (never hardcoded).
 */
function ${fnPrefix}_setup() {
    add_theme_support( 'title-tag' );
    add_theme_support( 'post-thumbnails' );
    add_theme_support( 'custom-logo', array( 'height' => 96, 'width' => 256, 'flex-height' => true, 'flex-width' => true ) );
    add_theme_support( 'html5', array( 'search-form', 'gallery', 'caption', 'style', 'script' ) );
    register_nav_menus( array(
        'primary' => __( 'Primary Menu', '${slug}' ),
        'footer'  => __( 'Footer Menu', '${slug}' ),
    ) );
}
add_action( 'after_setup_theme', '${fnPrefix}_setup' );

function ${fnPrefix}_assets() {
    wp_enqueue_style( '${slug}-fonts', 'https://fonts.googleapis.com/css2?family=${fonts.display.split(',')[0].replace(/ /g, '+')}:wght@500;700&display=swap', array(), null );
    wp_enqueue_style( '${slug}-style', get_stylesheet_uri(), array( '${slug}-fonts' ), '1.0.0' );
}
add_action( 'wp_enqueue_scripts', '${fnPrefix}_assets' );
`,
  )

  // ---- header.php ----
  push(
    'header.php',
    `<!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
<header class="rr-header">
  <div class="rr-wrap rr-nav">
    <a href="<?php echo esc_url( home_url( '/' ) ); ?>" class="rr-logo"><?php bloginfo( 'name' ); ?></a>
    <?php wp_nav_menu( array( 'theme_location' => 'primary', 'container' => false, 'menu_class' => 'rr-menu' ) ); ?>
    <a class="rr-cta" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Get in touch</a>
  </div>
</header>
<main id="content">
`,
  )

  // ---- footer.php ----
  push(
    'footer.php',
    `</main>
<footer class="rr-footer">
  <div class="rr-wrap">
    <div class="rr-grid">
      <div>
        <h3><?php bloginfo( 'name' ); ?></h3>
        <p><?php bloginfo( 'description' ); ?></p>
      </div>
      <div>
        <h3>Explore</h3>
        <?php wp_nav_menu( array( 'theme_location' => 'footer', 'container' => false, 'menu_class' => 'rr-menu' ) ); ?>
      </div>
      <div>
        <h3>Contact</h3>
        <p><?php echo esc_html( get_theme_mod( 'rr_contact_line', 'Write to us through the contact page.' ) ); ?></p>
      </div>
    </div>
  </div>
</footer>
<?php wp_footer(); ?>
</body>
</html>
`,
  )

  // ---- front-page.php: hero + latest cards ----
  push(
    'front-page.php',
    `<?php get_header(); ?>
<section class="rr-hero">
  <div class="rr-wrap">
    <h1><?php echo esc_html( get_theme_mod( 'rr_hero_title', '${identity.brand}' ) ); ?></h1>
    <p><?php echo esc_html( get_theme_mod( 'rr_hero_tagline', '${identity.tagline}' ) ); ?></p>
  </div>
</section>
<section class="rr-section">
  <div class="rr-wrap rr-grid">
    <?php
    $rr_latest = new WP_Query( array( 'posts_per_page' => 3 ) );
    while ( $rr_latest->have_posts() ) :
        $rr_latest->the_post();
        ?>
        <article class="rr-card">
          <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
          <p><?php echo esc_html( wp_trim_words( get_the_excerpt(), 24 ) ); ?></p>
        </article>
        <?php
    endwhile;
    wp_reset_postdata();
    ?>
  </div>
</section>
<?php get_footer(); ?>
`,
  )

  // ---- index.php ----
  push(
    'index.php',
    `<?php get_header(); ?>
<section class="rr-section">
  <div class="rr-wrap">
    <?php if ( have_posts() ) : ?>
      <?php while ( have_posts() ) : the_post(); ?>
        <article <?php post_class( 'rr-card' ); ?>>
          <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
          <?php the_excerpt(); ?>
        </article>
      <?php endwhile; ?>
      <div class="rr-pagination"><?php the_posts_pagination(); ?></div>
    <?php else : ?>
      <p><?php esc_html_e( 'Nothing published yet.', '${slug}' ); ?></p>
    <?php endif; ?>
  </div>
</section>
<?php get_footer(); ?>
`,
  )

  // ---- single.php, page.php, archive.php, search.php, 404.php ----
  push(
    'single.php',
    `<?php get_header(); ?>
<?php while ( have_posts() ) : the_post(); ?>
  <article class="rr-section">
    <div class="rr-wrap">
      <h1><?php the_title(); ?></h1>
      <div class="entry-content"><?php the_content(); ?></div>
    </div>
  </article>
<?php endwhile; ?>
<?php get_footer(); ?>
`,
  )
  push(
    'page.php',
    `<?php get_header(); ?>
<?php while ( have_posts() ) : the_post(); ?>
  <article class="rr-section">
    <div class="rr-wrap">
      <h1><?php the_title(); ?></h1>
      <div class="entry-content"><?php the_content(); ?></div>
    </div>
  </article>
<?php endwhile; ?>
<?php get_footer(); ?>
`,
  )
  push(
    'archive.php',
    `<?php get_header(); ?>
<section class="rr-section">
  <div class="rr-wrap">
    <h1><?php the_archive_title(); ?></h1>
    <?php while ( have_posts() ) : the_post(); ?>
      <article class="rr-card"><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2></article>
    <?php endwhile; ?>
  </div>
</section>
<?php get_footer(); ?>
`,
  )
  push(
    'search.php',
    `<?php get_header(); ?>
<section class="rr-section">
  <div class="rr-wrap">
    <h1><?php echo esc_html( get_search_query() ? 'Results for: ' . get_search_query() : 'Search' ); ?></h1>
    <?php get_search_form(); ?>
    <?php while ( have_posts() ) : the_post(); ?>
      <article class="rr-card"><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2></article>
    <?php endwhile; ?>
  </div>
</section>
<?php get_footer(); ?>
`,
  )
  push(
    '404.php',
    `<?php get_header(); ?>
<section class="rr-section">
  <div class="rr-wrap">
    <h1>Page not found</h1>
    <p>The page you asked for is not here. Try the search below.</p>
    <?php get_search_form(); ?>
  </div>
</section>
<?php get_footer(); ?>
`,
  )

  // ---- README with the honest verification status ----
  push(
    'README.txt',
    `${identity.brand}
Generated by ROYAL RED on ${new Date().toISOString().slice(0, 10)}

INSTALL
1. Zip the theme folder (or use the provided zip) and upload it in WP Admin, Appearance, Themes, Add New, Upload.
2. Activate, then set a Static front page (Settings, Reading) for the hero layout.
3. Assign menus to the Primary and Footer locations (Appearance, Menus).

VERIFICATION STATUS
Static Theme-Check-style audit: run in this build (see the receipt).
Live WordPress verification: pending. This theme was not executed inside a
real WordPress install because the generating environment has no PHP runtime.
Every structural claim in the audit is a static check, stated honestly.
`,
  )

  // ---- static Theme-Check-style audit ----
  const joined = files.map((f) => f.content).join('\n')
  const checks: WpCheck[] = [
    { name: 'style.css has the WordPress theme header', pass: /Theme Name:/i.test(files[0].content) && /Author:/i.test(files[0].content) },
    {
      name: 'required templates present',
      pass: ['index.php', 'header.php', 'footer.php', 'single.php', 'page.php', 'archive.php', 'search.php', '404.php', 'front-page.php', 'functions.php', 'style.css'].every((f) => files.some((x) => x.path === f)),
      detail: `${files.length} files`,
    },
    { name: 'styles + scripts enqueue via wp_enqueue_scripts', pass: /wp_enqueue_style/.test(joined) && /add_action\( 'wp_enqueue_scripts'/.test(joined) },
    { name: 'no hardcoded <link> stylesheet tags', pass: !/<link[^>]+stylesheet/i.test(joined) },
    { name: 'registers a menu location', pass: /register_nav_menus/.test(joined) },
    { name: 'theme supports: title-tag, thumbnails, custom-logo', pass: /add_theme_support\( 'title-tag' \)/.test(joined) && /post-thumbnails/.test(joined) && /custom-logo/.test(joined) },
    { name: 'language_attributes + body_class present', pass: /language_attributes/.test(joined) && /body_class/.test(joined) },
    { name: 'text law: no emojis, no em or en dashes', pass: !/\p{Extended_Pictographic}|—|–/u.test(joined) },
  ]
  const passed = checks.filter((c) => c.pass).length
  const status: WpThemeReport['status'] = passed === checks.length ? 'static-audit-pass' : 'static-audit-fail'

  return {
    slug,
    themeName: identity.brand,
    files,
    checks,
    status,
    verificationLabel: 'verification pending real WordPress',
    summary: `${identity.brand}: ${files.length} theme files, static audit ${passed}/${checks.length}. Live WordPress verification pending (no PHP runtime here), stated honestly on the receipt.`,
  }
}

// package the theme (or theme + full-package manifest) into a zip Buffer
export function packageWpTheme(report: WpThemeReport, mode: 'theme' | 'full'): Buffer {
  const root = `${report.slug}/`
  const files = report.files.map((f) => ({ path: root + f.path, content: f.content }))
  if (mode === 'full') {
    files.push({
      path: root + 'plugins-manifest.json',
      content: JSON.stringify(
        {
          recommended: [
            { slug: 'wordpress-seo', reason: 'meta + sitemap management' },
            { slug: 'wp-super-cache', reason: 'page caching' },
            { slug: 'wordfence', reason: 'security scanning' },
          ],
          note: 'install through WP Admin, Plugins, Add New; none are required for the theme to activate',
        },
        null,
        2,
      ),
    })
    files.push({
      path: root + 'INSTALL-FULL.md',
      content: 'FULL PACKAGE\n\n1. Upload and activate the theme (Appearance, Themes, Add New, Upload).\n2. Install the plugins listed in plugins-manifest.json (Plugins, Add New).\n3. Set a static front page and assign menus.\n\nPackage generated by ROYAL RED.\n',
    })
  }
  return buildZip(files)
}
